export const boardList = [
  {
    id: 1,
    gridSize: 5,
    exitDoor: "C1",
    data: [
      {
        startAt: "A1",
        cellCount: 3,
        color: "blue",
        isVertical: false,
      },
      {
        startAt: "B1",
        cellCount: 2,
        color: "purple",
        isVertical: true,
      },
      {
        startAt: "A4",
        cellCount: 2,
        color: "gray",
        isVertical: true,
      },
      {
        startAt: "C4",
        cellCount: 2,
        color: "red",
        isVertical: false,
      },
      {
        startAt: "F3",
        cellCount: 2,
        color: "yellow",
        isVertical: false,
      },
    ],
  },
  {
    id: 2,
    gridSize: 5,
    exitDoor: "D1",
    data: [
      {
        startAt: "A1",
        cellCount: 3,
        color: "blue",
        isVertical: false,
      },
      {
        startAt: "C4",
        cellCount: 2,
        color: "red",
        isVertical: false,
      },
      {
        startAt: "D1",
        cellCount: 2,
        color: "forestgreen",
        isVertical: false,
      },
      {
        startAt: "D3",
        cellCount: 2,
        color: "orange",
        isVertical: true,
      },
      {
        startAt: "F3",
        cellCount: 2,
        color: "yellow",
        isVertical: false,
      },
    ],
  },
  {
    id: 3,
    gridSize: 5,
    exitDoor: "B1",
    data: [
      {
        startAt: "A1",
        cellCount: 3,
        color: "blue",
        isVertical: false,
      },
      {
        startAt: "B1",
        cellCount: 2,
        color: "purple",
        isVertical: true,
      },
      {
        startAt: "C4",
        cellCount: 2,
        color: "red",
        isVertical: false,
      },
      {
        startAt: "D1",
        cellCount: 2,
        color: "forestgreen",
        isVertical: false,
      },
      {
        startAt: "D3",
        cellCount: 2,
        color: "orange",
        isVertical: true,
      },
      {
        startAt: "F3",
        cellCount: 2,
        color: "yellow",
        isVertical: false,
      },
    ],
  },
  {
    id: 4,
    gridSize: 5,
    exitDoor: "A3",
    data: [
      {
        startAt: "B1",
        cellCount: 2,
        color: "purple",
        isVertical: true,
      },
      {
        startAt: "A4",
        cellCount: 2,
        color: "gray",
        isVertical: true,
      },
      {
        startAt: "C4",
        cellCount: 2,
        color: "red",
        isVertical: false,
      },
      {
        startAt: "D1",
        cellCount: 2,
        color: "forestgreen",
        isVertical: false,
      },
      {
        startAt: "D3",
        cellCount: 2,
        color: "orange",
        isVertical: true,
      },
      {
        startAt: "F3",
        cellCount: 2,
        color: "yellow",
        isVertical: false,
      },
    ],
  },
  {
    id: 5,
    gridSize: 5,
    exitDoor: "B5",
    data: [
      {
        startAt: "A1",
        cellCount: 3,
        color: "blue",
        isVertical: false,
      },
      {
        startAt: "B1",
        cellCount: 2,
        color: "purple",
        isVertical: true,
      },
      {
        startAt: "A4",
        cellCount: 2,
        color: "gray",
        isVertical: true,
      },
      {
        startAt: "C4",
        cellCount: 2,
        color: "red",
        isVertical: false,
      },
      {
        startAt: "D1",
        cellCount: 2,
        color: "forestgreen",
        isVertical: false,
      },
      {
        startAt: "D3",
        cellCount: 2,
        color: "orange",
        isVertical: true,
      },
    ],
  },
  {
    id: 6,
    gridSize: 5,
    exitDoor: "D5",
    data: [
      {
        startAt: "A1",
        cellCount: 3,
        color: "blue",
        isVertical: false,
      },
      {
        startAt: "B1",
        cellCount: 2,
        color: "purple",
        isVertical: true,
      },
      {
        startAt: "A4",
        cellCount: 2,
        color: "gray",
        isVertical: true,
      },
      {
        startAt: "C4",
        cellCount: 2,
        color: "red",
        isVertical: false,
      },
      {
        startAt: "D3",
        cellCount: 2,
        color: "orange",
        isVertical: true,
      },
      {
        startAt: "F3",
        cellCount: 2,
        color: "yellow",
        isVertical: false,
      },
    ],
  },
  {
    id: 7,
    gridSize: 5,
    exitDoor: "C4",
    data: [
      {
        startAt: "A1",
        cellCount: 3,
        color: "blue",
        isVertical: false,
      },
      {
        startAt: "B1",
        cellCount: 2,
        color: "purple",
        isVertical: true,
      },
      {
        startAt: "C4",
        cellCount: 2,
        color: "red",
        isVertical: false,
      },
      {
        startAt: "D1",
        cellCount: 2,
        color: "forestgreen",
        isVertical: false,
      },
      {
        startAt: "D3",
        cellCount: 2,
        color: "orange",
        isVertical: true,
      },
      {
        startAt: "F3",
        cellCount: 2,
        color: "yellow",
        isVertical: false,
      },
    ],
  },
  {
    id: 8,
    gridSize: 5,
    exitDoor: "E5",
    data: [
      {
        startAt: "A1",
        cellCount: 3,
        color: "blue",
        isVertical: false,
      },
      {
        startAt: "B1",
        cellCount: 2,
        color: "purple",
        isVertical: true,
      },
      {
        startAt: "A4",
        cellCount: 2,
        color: "gray",
        isVertical: true,
      },
      {
        startAt: "C4",
        cellCount: 2,
        color: "red",
        isVertical: false,
      },
      {
        startAt: "D1",
        cellCount: 2,
        color: "forestgreen",
        isVertical: false,
      },
      {
        startAt: "D3",
        cellCount: 2,
        color: "orange",
        isVertical: true,
      },
    ],
  },
  {
    id: 9,
    gridSize: 5,
    exitDoor: "F5",
    data: [
      {
        startAt: "A1",
        cellCount: 3,
        color: "blue",
        isVertical: false,
      },
      {
        startAt: "B1",
        cellCount: 2,
        color: "purple",
        isVertical: true,
      },
      {
        startAt: "A4",
        cellCount: 2,
        color: "gray",
        isVertical: true,
      },
      {
        startAt: "C4",
        cellCount: 2,
        color: "red",
        isVertical: false,
      },
      {
        startAt: "D3",
        cellCount: 2,
        color: "orange",
        isVertical: true,
      },
      {
        startAt: "F3",
        cellCount: 2,
        color: "yellow",
        isVertical: false,
      },
    ],
  },
  {
    id: 10,
    gridSize: 5,
    exitDoor: "A2",
    data: [
      {
        startAt: "A1",
        cellCount: 3,
        color: "blue",
        isVertical: false,
      },
      {
        startAt: "B1",
        cellCount: 2,
        color: "purple",
        isVertical: true,
      },
      {
        startAt: "A4",
        cellCount: 2,
        color: "gray",
        isVertical: true,
      },
      {
        startAt: "C4",
        cellCount: 2,
        color: "red",
        isVertical: false,
      },
      {
        startAt: "D3",
        cellCount: 2,
        color: "orange",
        isVertical: true,
      },
      {
        startAt: "F3",
        cellCount: 2,
        color: "yellow",
        isVertical: false,
      },
    ],
  },
  {
    id: 11,
    gridSize: 6,
    exitDoor: "C1",
    data: [
      {
        startAt: "A4",
        cellCount: 3,
        color: "gray",
        isVertical: true,
      },
      {
        startAt: "A5",
        cellCount: 2,
        color: "yellow",
        isVertical: true,
      },
      {
        startAt: "A6",
        cellCount: 2,
        color: "green",
        isVertical: true,
      },
      {
        startAt: "C5",
        cellCount: 2,
        color: "red",
        isVertical: false,
      },
      {
        startAt: "D1",
        cellCount: 2,
        color: "forestgreen",
        isVertical: false,
      },
      {
        startAt: "E2",
        cellCount: 2,
        color: "blue",
        isVertical: true,
      },
      {
        startAt: "F5",
        cellCount: 2,
        color: "black",
        isVertical: false,
      },
      {
        startAt: "E5",
        cellCount: 2,
        color: "slategray",
        isVertical: false,
      },
    ],
  },
  {
    id: 12,
    gridSize: 6,
    exitDoor: "D1",
    data: [
      {
        startAt: "A1",
        cellCount: 3,
        color: "blue",
        isVertical: false,
      },
      {
        startAt: "B1",
        cellCount: 2,
        color: "purple",
        isVertical: true,
      },
      {
        startAt: "A4",
        cellCount: 3,
        color: "gray",
        isVertical: true,
      },
      {
        startAt: "A5",
        cellCount: 2,
        color: "yellow",
        isVertical: true,
      },
      {
        startAt: "A6",
        cellCount: 2,
        color: "green",
        isVertical: true,
      },
      {
        startAt: "C5",
        cellCount: 2,
        color: "red",
        isVertical: false,
      },
      {
        startAt: "D1",
        cellCount: 2,
        color: "forestgreen",
        isVertical: false,
      },
      {
        startAt: "E2",
        cellCount: 2,
        color: "blue",
        isVertical: true,
      },
      {
        startAt: "D3",
        cellCount: 2,
        color: "orange",
        isVertical: true,
      },
      {
        startAt: "F3",
        cellCount: 2,
        color: "yellow",
        isVertical: false,
      },
      {
        startAt: "F5",
        cellCount: 2,
        color: "black",
        isVertical: false,
      },
      {
        startAt: "E5",
        cellCount: 2,
        color: "slategray",
        isVertical: false,
      },
    ],
  },
  {
    id: 13,
    gridSize: 6,
    exitDoor: "F1",
    data: [
      {
        startAt: "A1",
        cellCount: 3,
        color: "blue",
        isVertical: false,
      },
      {
        startAt: "B1",
        cellCount: 2,
        color: "purple",
        isVertical: true,
      },
      {
        startAt: "A4",
        cellCount: 3,
        color: "gray",
        isVertical: true,
      },
      {
        startAt: "C5",
        cellCount: 2,
        color: "red",
        isVertical: false,
      },
      {
        startAt: "D1",
        cellCount: 2,
        color: "forestgreen",
        isVertical: false,
      },
      {
        startAt: "E2",
        cellCount: 2,
        color: "blue",
        isVertical: true,
      },
      {
        startAt: "D3",
        cellCount: 2,
        color: "orange",
        isVertical: true,
      },
      {
        startAt: "F3",
        cellCount: 2,
        color: "yellow",
        isVertical: false,
      },
    ],
  },
  {
    id: 14,
    gridSize: 6,
    exitDoor: "A5",
    data: [
      {
        startAt: "A1",
        cellCount: 3,
        color: "blue",
        isVertical: false,
      },
      {
        startAt: "A4",
        cellCount: 3,
        color: "gray",
        isVertical: true,
      },
      {
        startAt: "A5",
        cellCount: 2,
        color: "yellow",
        isVertical: true,
      },
      {
        startAt: "A6",
        cellCount: 2,
        color: "green",
        isVertical: true,
      },
      {
        startAt: "C5",
        cellCount: 2,
        color: "red",
        isVertical: false,
      },
      {
        startAt: "D1",
        cellCount: 2,
        color: "forestgreen",
        isVertical: false,
      },
      {
        startAt: "E2",
        cellCount: 2,
        color: "blue",
        isVertical: true,
      },
      {
        startAt: "D3",
        cellCount: 2,
        color: "orange",
        isVertical: true,
      },
    ],
  },
  {
    id: 15,
    gridSize: 6,
    exitDoor: "F4",
    data: [
      {
        startAt: "B1",
        cellCount: 2,
        color: "purple",
        isVertical: true,
      },
      {
        startAt: "A4",
        cellCount: 3,
        color: "gray",
        isVertical: true,
      },
      {
        startAt: "A5",
        cellCount: 2,
        color: "yellow",
        isVertical: true,
      },
      {
        startAt: "A6",
        cellCount: 2,
        color: "green",
        isVertical: true,
      },
      {
        startAt: "C5",
        cellCount: 2,
        color: "red",
        isVertical: false,
      },
      {
        startAt: "D3",
        cellCount: 2,
        color: "orange",
        isVertical: true,
      },
      {
        startAt: "F3",
        cellCount: 2,
        color: "yellow",
        isVertical: false,
      },
      {
        startAt: "F5",
        cellCount: 2,
        color: "black",
        isVertical: false,
      },
      {
        startAt: "E5",
        cellCount: 2,
        color: "slategray",
        isVertical: false,
      },
    ],
  },
  {
    id: 16,
    gridSize: 6,
    exitDoor: "C6",
    data: [
      {
        startAt: "A1",
        cellCount: 3,
        color: "blue",
        isVertical: false,
      },
      {
        startAt: "B1",
        cellCount: 2,
        color: "purple",
        isVertical: true,
      },
      {
        startAt: "A4",
        cellCount: 3,
        color: "gray",
        isVertical: true,
      },
      {
        startAt: "A5",
        cellCount: 2,
        color: "yellow",
        isVertical: true,
      },
      {
        startAt: "A6",
        cellCount: 2,
        color: "green",
        isVertical: true,
      },
      {
        startAt: "C5",
        cellCount: 2,
        color: "red",
        isVertical: false,
      },
      {
        startAt: "E2",
        cellCount: 2,
        color: "blue",
        isVertical: true,
      },
      {
        startAt: "D3",
        cellCount: 2,
        color: "orange",
        isVertical: true,
      },
      {
        startAt: "F3",
        cellCount: 2,
        color: "yellow",
        isVertical: false,
      },
      {
        startAt: "F5",
        cellCount: 2,
        color: "black",
        isVertical: false,
      },
    ],
  },
  {
    id: 17,
    gridSize: 6,
    exitDoor: "B4",
    data: [
      {
        startAt: "A1",
        cellCount: 3,
        color: "blue",
        isVertical: false,
      },
      {
        startAt: "B1",
        cellCount: 2,
        color: "purple",
        isVertical: true,
      },
      {
        startAt: "A4",
        cellCount: 3,
        color: "gray",
        isVertical: true,
      },
      {
        startAt: "A5",
        cellCount: 2,
        color: "yellow",
        isVertical: true,
      },
      {
        startAt: "A6",
        cellCount: 2,
        color: "green",
        isVertical: true,
      },
      {
        startAt: "C5",
        cellCount: 2,
        color: "red",
        isVertical: false,
      },
      {
        startAt: "D1",
        cellCount: 2,
        color: "forestgreen",
        isVertical: false,
      },
      {
        startAt: "D3",
        cellCount: 2,
        color: "orange",
        isVertical: true,
      },
      {
        startAt: "F3",
        cellCount: 2,
        color: "yellow",
        isVertical: false,
      },
      {
        startAt: "F5",
        cellCount: 2,
        color: "black",
        isVertical: false,
      },
      {
        startAt: "E5",
        cellCount: 2,
        color: "slategray",
        isVertical: false,
      },
    ],
  },
  {
    id: 18,
    gridSize: 6,
    exitDoor: "E6",
    data: [
      {
        startAt: "A1",
        cellCount: 3,
        color: "blue",
        isVertical: false,
      },
      {
        startAt: "B1",
        cellCount: 2,
        color: "purple",
        isVertical: true,
      },
      {
        startAt: "A4",
        cellCount: 3,
        color: "gray",
        isVertical: true,
      },
      {
        startAt: "A5",
        cellCount: 2,
        color: "yellow",
        isVertical: true,
      },
      {
        startAt: "A6",
        cellCount: 2,
        color: "green",
        isVertical: true,
      },
      {
        startAt: "C5",
        cellCount: 2,
        color: "red",
        isVertical: false,
      },
      {
        startAt: "D1",
        cellCount: 2,
        color: "forestgreen",
        isVertical: false,
      },
      {
        startAt: "E2",
        cellCount: 2,
        color: "blue",
        isVertical: true,
      },
      {
        startAt: "D3",
        cellCount: 2,
        color: "orange",
        isVertical: true,
      },
      {
        startAt: "F3",
        cellCount: 2,
        color: "yellow",
        isVertical: false,
      },
      {
        startAt: "F5",
        cellCount: 2,
        color: "black",
        isVertical: false,
      },
      {
        startAt: "E5",
        cellCount: 2,
        color: "slategray",
        isVertical: false,
      },
    ],
  },
  {
    id: 19,
    gridSize: 6,
    exitDoor: "E1",
    data: [
      {
        startAt: "A1",
        cellCount: 3,
        color: "blue",
        isVertical: false,
      },
      {
        startAt: "B1",
        cellCount: 2,
        color: "purple",
        isVertical: true,
      },
      {
        startAt: "A4",
        cellCount: 3,
        color: "gray",
        isVertical: true,
      },
      {
        startAt: "A5",
        cellCount: 2,
        color: "yellow",
        isVertical: true,
      },
      {
        startAt: "A6",
        cellCount: 2,
        color: "green",
        isVertical: true,
      },
      {
        startAt: "C5",
        cellCount: 2,
        color: "red",
        isVertical: false,
      },
      {
        startAt: "D1",
        cellCount: 2,
        color: "forestgreen",
        isVertical: false,
      },
      {
        startAt: "E2",
        cellCount: 2,
        color: "blue",
        isVertical: true,
      },
      {
        startAt: "D3",
        cellCount: 2,
        color: "orange",
        isVertical: true,
      },
      {
        startAt: "F3",
        cellCount: 2,
        color: "yellow",
        isVertical: false,
      },
      {
        startAt: "F5",
        cellCount: 2,
        color: "black",
        isVertical: false,
      },
      {
        startAt: "E5",
        cellCount: 2,
        color: "slategray",
        isVertical: false,
      },
    ],
  },
  {
    id: 20,
    gridSize: 6,
    exitDoor: "C1",
    data: [
      {
        startAt: "A1",
        cellCount: 3,
        color: "blue",
        isVertical: false,
      },
      {
        startAt: "B1",
        cellCount: 2,
        color: "purple",
        isVertical: true,
      },
      {
        startAt: "A4",
        cellCount: 3,
        color: "gray",
        isVertical: true,
      },
      {
        startAt: "A5",
        cellCount: 2,
        color: "yellow",
        isVertical: true,
      },
      {
        startAt: "A6",
        cellCount: 2,
        color: "green",
        isVertical: true,
      },
      {
        startAt: "C5",
        cellCount: 2,
        color: "red",
        isVertical: false,
      },
      {
        startAt: "D1",
        cellCount: 2,
        color: "forestgreen",
        isVertical: false,
      },
      {
        startAt: "E2",
        cellCount: 2,
        color: "blue",
        isVertical: true,
      },
      {
        startAt: "D3",
        cellCount: 2,
        color: "orange",
        isVertical: true,
      },
      {
        startAt: "F3",
        cellCount: 2,
        color: "yellow",
        isVertical: false,
      },
      {
        startAt: "F5",
        cellCount: 2,
        color: "black",
        isVertical: false,
      },
      {
        startAt: "E5",
        cellCount: 2,
        color: "slategray",
        isVertical: false,
      },
    ],
  },
];
